FROM klee/klee AS deps
ARG DEBIAN_FRONTEND=noninteractive

USER root

# Fix broken Kitware package feed (VMF needs CMake).
RUN set -eux \
    && test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-get update

# General dependencies
RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends --fix-missing \
        ca-certificates \
        cmake \
        curl \
        gdb \
        git \
        gnupg \
        lsb-core \
        lsb-release

# Development dependencies
RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends --fix-missing \
        build-essential \
        clang \
        doxygen \
        graphviz \
        libcurl4-openssl-dev \
        lld \
        llvm \
        llvm-dev \
        python3-dev \
        python3-pip \
        python3-setuptools \
        libselinux1-dev

FROM deps AS aflpp

# Clone and build firejail
RUN git clone --depth 1 https://github.com/netblue30/firejail.git /usr/local/src/firejail\
    && cd /usr/local/src/firejail \
    && ./configure --prefix=/usr --enable-selinux \
    && make \
    && make install-strip 
    
# Clone and build AFL++
RUN set -eux \
    && cd /usr/local/src \
    && git clone --depth 1 -b v5.00c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install \
    && command -v afl-cc \
    && command -v afl-fuzz \
    && command -v afl-showmap \
    && afl-cc --version \
    && afl-cc --help

FROM aflpp AS vmf

# Clone, build, install VMF
RUN set -eux \
    && cd /usr/local/src \
    && mkdir vmf \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf \
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make install \
    && command -v vader \
    && vader --help

USER klee

# Verify installed AFL++ and VMF commands can start
RUN set -eux \
    && command -v afl-cc \
    && command -v afl-fuzz \
    && command -v vader