FROM quay.io/centos/centos:stream8 AS deps

# https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/CentOS-*.repo && \
    sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/CentOS-*.repo && \
    sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/CentOS-*.repo


# General dependencies
RUN dnf install --assumeyes \
       ca-certificates \
       libcurl-minimal \
       gdb \
       git \
       gnupg

# Development dependencies
RUN dnf install --assumeyes  \
        clang \
        libcurl-devel \
        llvm \
        python3-devel \
        python3-pip \
        python3-setuptools \
        cmake \
        zlib-devel

# Remaining LLVM tools
RUN dnf install --assumeyes \
        lld \
        llvm-devel 

ENV LLVM_CONFIG=llvm-config-17

RUN pip3 install --user wheel

FROM deps AS aflpp

# AFL++ build dependencies
# Currently gcc plugin version don't match available gcc version. This is necessary for some AFL++ modes.
RUN dnf install --assumeyes \
        automake \
        cpio \
        glib2-devel \
        flex \
        bison \
        cargo

# Clone and build AFL++
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 -b v4.30c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install \
    && set +ex

FROM aflpp AS vmf

# Clone, build, install VMF
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf\
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j \
    && make install \
    && set +ex
    