FROM klee/klee AS deps

USER root

RUN test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends --fix-missing \
    ca-certificates \
    curl \
    gdb \
    git \
    gnupg \
    lsb-core \
    lsb-release \
    cmake=3.28.3-0kitware1ubuntu22.04.1

RUN lsb_release -a | grep -q "18.04" && ( \
      echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main" >> /etc/apt/sources.list && \
      curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    ) || \
    (lsb_release -a | grep -q "20.04") || \
    (lsb_release -a | grep -q "22.04") || (echo "Ubuntu 18.04, 20.04, or 22.04 required!!!" >&2; exit 1)

RUN apt-get update \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --fix-missing \
       graphviz \
       clang-14 \
       doxygen \
       libcurl4-openssl-dev \
       llvm-14 \
       llvm-14-dev \
       python3-dev \
       python3-pip \
       python3-setuptools \
       build-essential \
       lld-14 


ENV LLVM_CONFIG=llvm-config

FROM deps AS aflpp

# Clone and build AFL++
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 -b v4.30c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install 


FROM aflpp AS vmf

# Clone, build, install VMF
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf\
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j 8 \
    && make install \
    && set +ex

USER klee