FROM ubuntu:20.04 AS deps

RUN  apt-get update \
     && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends --fix-missing \
       ca-certificates \
       curl \
       gdb \
       git \
       gnupg \
       lsb-core \
       lsb-release \
       zip

# must trust Draper list of certificates including issuing certificate
RUN curl -L https://network-public.pages.draper.com/sslbundle/ca-certificates.crt >> /usr/local/share/ca-certificates/ca-certificates.crt \
    && update-ca-certificates \
    && git config --global http.sslCAInfo /usr/local/share/ca-certificates/ca-certificates.crt

RUN lsb_release -a | grep -q "18.04" && ( \
      echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main" >> /etc/apt/sources.list && \
      curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    ) || \
    (lsb_release -a | grep -q "20.04") || \
    (lsb_release -a | grep -q "22.04") || (echo "Ubuntu 18.04, 20.04, or 22.04 required!!!" >&2; exit 1)

RUN  apt-get update \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --fix-missing \
       graphviz \
       clang-12 \
       doxygen \
       libcurl4-openssl-dev \
       llvm-12 \
       llvm-12-dev \
       python3-dev \
       python3-pip \
       python3-setuptools \
       build-essential \
       cmake

ENV  LLVM_CONFIG=llvm-config-12
RUN set -ex \
    && cd `$LLVM_CONFIG --bindir` \
    && for f in *; do rm -f /usr/bin/$f; ln -s ../lib/llvm-12/bin/$f /usr/bin/$f; done \
    && set +ex


# # Due to issues with GnuTLS behind proxies we need to rebuild git from source in order for it to use OpenSSL instead
# https://github.com/argoproj/argo-cd/issues/3994
RUN update-ca-certificates \
    && cd /usr/local/src \
    && curl https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.9.5.tar.gz -o git-2.9.5.tar.gz \
    && tar -zxf git-2.9.5.tar.gz \
    && cd git-2.9.5 \
    && make configure \
    && ./configure --prefix=/usr \
    && make all \
    && make install

FROM deps AS aflpp

# Clone and build AFL++
# https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutls
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 -b v4.30c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install \
    && set +ex
    
FROM aflpp AS vmf

# Clone, build, install VMF
# https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutls
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf \
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j \
    && make install \
    && set +ex
