FROM quay.io/centos/centos:stream9 AS deps


# General dependencies
RUN dnf install --assumeyes \
       ca-certificates \
       curl-minimal \
       gdb \
       git \
       gnupg

# Development dependencies
RUN  dnf install --assumeyes  \
        clang-18.1.8 \
        libcurl-devel \
        llvm-18.1.8 \
        python3-devel \
        python3-pip \
        python3-setuptools \
        cmake \
        zlib-devel

# Remaining LLVM tools
RUN dnf install --assumeyes \
        lld-18.1.8 \
        llvm-devel-18.1.8 

ENV LLVM_CONFIG=llvm-config-18

FROM deps AS aflpp

# AFL++ build dependencies
# Currently gcc plugin version don't match available gcc version. This is necessary for some AFL++ modes.
RUN dnf install --assumeyes \
        automake \
        cpio \
        glib2-devel \
        flex \
        bison \
        cargo


# Clone and build AFL++
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 -b v4.30c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install \
    && set +ex

FROM aflpp AS vmf

# Clone, build, install VMF
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf\
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j 8 \
    && make install \
    && set +ex
