FROM oraclelinux:8 AS deps

RUN  dnf install --assumeyes \
       ca-certificates \
       curl \
       gdb \
       git \
       gnupg

RUN  dnf install --assumeyes \
       graphviz \
       clang \
       libcurl-devel \
       llvm \
       llvm-devel \
       lld \
       python3-devel \
       python3-pip \
       python3-setuptools \
       cmake \
       zlib-devel

ENV LLVM_CONFIG=llvm-config-18

FROM deps AS aflpp


# Clone and build AFL++
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 -b v4.30c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install \
    && set +ex

FROM aflpp AS vmf

# Clone, build, install VMF
RUN set -ex \
    && cd /usr/local/src \
    && mkdir vmf \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf \
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j \
    && make install \
    && set +ex
