FROM kalilinux/kali-last-release AS deps

RUN  apt-get update \
     && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends --fix-missing \
       ca-certificates \
       curl \
       gdb \
       git \
       gnupg \
       lsb-release \
       zip

RUN  apt-get update \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --fix-missing \
       graphviz \
       clang-16 \
       libclang-rt-16-dev \
       clang \
       doxygen \
       libcurl4-openssl-dev \
       llvm-16 \
       llvm-16-dev \
       llvm \
       llvm-dev \
       lld \
       python3-dev \
       python3-pip \
       python3-setuptools \
       build-essential \
       cmake

ENV  LLVM_CONFIG=llvm-config-16

FROM deps AS aflpp

# Clone and build AFL++
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 -b v4.30c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install \
    && set +ex
    
FROM aflpp AS vmf

# Clone, build, install VMF
RUN set -ex \
    && cd /usr/local/src \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf\
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j \
    && make install \
    && set +ex
    
