FROM ubuntu:22.04 AS deps
ARG DEBIAN_FRONTEND=noninteractive

# General dependencies
RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends --fix-missing \
        ca-certificates \
        curl \
        gdb \
        git \
        gnupg \
        lsb-release \
        zip

# Development dependencies
RUN set -eux \
    && apt-get install -y --no-install-recommends --fix-missing \
        build-essential \
        clang \
        cmake \
        doxygen \
        graphviz \
        libcurl4-openssl-dev \
        lld \
        llvm \
        llvm-dev \
        python3-dev \
        python3-pip \
        python3-setuptools \
        libselinux1-dev

FROM deps AS aflpp

# Clone and build firejail
RUN git clone --depth 1 https://github.com/netblue30/firejail.git /usr/local/src/firejail\
    && cd /usr/local/src/firejail \
    && ./configure --prefix=/usr --enable-selinux \
    && make \
    && make install-strip 

# Clone and build AFL++
RUN set -eux \
    && cd /usr/local/src \
    && git clone --depth 1 -b v5.00c https://github.com/AFLplusplus/AFLplusplus.git \
    && cd AFLplusplus \
    && make all \
    && make install \
    && command -v afl-cc \
    && command -v afl-fuzz \
    && command -v afl-showmap \
    && afl-cc --version \
    && afl-cc --help

FROM aflpp AS vmf

# Clone, build, install VMF
RUN set -eux \
    && cd /usr/local/src \
    && mkdir vmf \
    && git clone --depth 1 https://github.com/draperlaboratory/vadermodularfuzzer.git vmf \
    && cd vmf \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j \
    && make install \
    && command -v vader
