#! /bin/sh

PROJECT_ROOT=$1
INSTALL_ROOT=$2
EXTERNAL_PRJ=$PROJECT_ROOT
cd $PROJECT_ROOT

[ ! -d "$INSTALL_ROOT" ] && mkdir $INSTALL_ROOT
[ ! -d "$INSTALL_ROOT/include" ] && mkdir $INSTALL_ROOT/include
[ ! -d "$INSTALL_ROOT/include/LibAFL-legacy" ] && mkdir $INSTALL_ROOT/include/LibAFL-legacy
[ ! -d "$INSTALL_ROOT/lib" ] && mkdir $INSTALL_ROOT/lib

cp $EXTERNAL_PRJ/LibAFL-legacy/libafl.so $INSTALL_ROOT/lib
cp $EXTERNAL_PRJ/LibAFL-legacy/include/* $INSTALL_ROOT/include/LibAFL-legacy

#
# AFL legacy headers have code that causes warnings we can't supress.  This
# patch fixes those so that we can compile our code with all warnings on, and
# force compilation errors on warnings.
#
cd $INSTALL_ROOT/include/LibAFL-legacy
patch < $PROJECT_ROOT/LibAFL-legacy.patch
cd $PROJECT_ROOT
