#! /bin/sh

PROJECT_ROOT=$1
INSTALL_ROOT=$2
EXTERNAL_PRJ=$PROJECT_ROOT
cd $PROJECT_ROOT

[ ! -d "$INSTALL_ROOT" ] && mkdir $INSTALL_ROOT
[ ! -d "$INSTALL_ROOT/include" ] && mkdir $INSTALL_ROOT/include
[ ! -d "$INSTALL_ROOT/include/plog" ] && mkdir $INSTALL_ROOT/include/plog

cp -r $EXTERNAL_PRJ/plog/include/plog/* $INSTALL_ROOT/include/plog

